#include "ft_printf.h"
#include <limits.h>
#include <stdio.h>

int	main(void)
{
	int	i;
	int	z;
	void *ptr;
	int	*intp;
	char *charp;
	char *strp;
	unsigned int *unsignedp;
	char *s;

	s = NULL;
	ft_putstr_fd("Test 1: Char\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %c\n", 'A');
	i = printf("Printf 2: %c\n", 'A');
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Char\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %c\n", 'A');
	i = printf("Printf 2: %c\n", 'A');
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Char\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %c\n", -1);
	i = printf("Printf 2: %c\n", -1);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", 0);
	i = printf("Printf 2: %i\n", 0);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", 10);
	i = ft_printf("Printf 1: %i\n", -10);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	z = printf("Printf 2: %i\n", 10);
	i = printf("Printf 2: %i\n", -10);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", 5324);
	i = ft_printf("Printf 1: %i\n", -5324);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	z = printf("Printf 2: %i\n", 5324);
	i = printf("Printf 2: %i\n", -5324);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", INT_MAX);
	i = ft_printf("Printf 1: %i\n", INT_MIN);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	z = printf("Printf 2: %i\n", INT_MAX);
	i = printf("Printf 2: %i\n", INT_MIN);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 5: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", NULL);
	i = printf("Printf 2: %i\n", NULL);
	printf("\nReturn: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "Hello World!");
	i = printf("Printf 2: %s\n\n", "Hello World!");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "asdasdasdasdasdsadasdasdasdasdasdsadsadsadsadsadsadad");
	i = printf("Printf 2: %s\n\n", "asdasdasdasdasdsadasdasdasdasdasdsadsadsadsadsadsadad");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "");
	i = printf("Printf 2: %s\n\n", "");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
	i = printf("Printf 2: %s\n\n", "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 5: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", s);
	i = printf("Printf 2: %s\n\n", s);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Pointer\n---------------\n\n", 1);
	int	a = 15;
	intp = &a;
	z = ft_printf("Printf 1: %p\n\n", intp);
	i = printf("Printf 2: %p\n\n", intp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Pointer\n---------------\n\n", 1);
	char	b = 'A';
	charp = &b;
	z = ft_printf("Printf 1: %p\n\n", charp);
	i = printf("Printf 2: %p\n\n", charp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: Pointer\n---------------\n\n", 1);
	char *c = "Hello";
	strp = c;
	z = ft_printf("Printf 1: %p\n\n", strp);
	i = printf("Printf 2: %p\n\n", strp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Pointer\n---------------\n\n", 1);
	unsigned int d = 40968;
	unsignedp = &d;
	z = ft_printf("Printf 1: %p\n\n", unsignedp);
	i = printf("Printf 2: %p\n\n", unsignedp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 5: Pointer\n---------------\n\n", 1);
	ptr = NULL;
	z = ft_printf("Printf 1: %p\n\n", ptr);
	i = printf("Printf 2: %p\n\n", ptr);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Unsigned int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %u\n\n", 0);
	i = printf("Printf 2: %u\n\n", 0);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Unsigned int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %u\n\n", 236326);
	i = printf("Printf 2: %u\n\n", 236326);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: Unsigned int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %u\n\n", UINT_MAX);
	i = printf("Printf 2: %u\n\n", UINT_MAX);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Unsigned int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %u\n\n", -1);
	i = printf("Printf 2: %u\n\n", -1);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", 0);
	i = printf("Printf 2: %x\n\n", 0);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", 44);
	i = printf("Printf 2: %x\n\n", 44);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", 155);
	i = printf("Printf 2: %x\n\n", 155);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", 356);
	i = printf("Printf 2: %x\n\n", 356);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 5: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", 34242);
	i = printf("Printf 2: %x\n\n", 34242);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 6: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", UINT_MAX);
	i = printf("Printf 2: %x\n\n", UINT_MAX);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 7: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", -1);
	i = printf("Printf 2: %x\n\n", -1);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 8: Hexa_Lower\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %x\n\n", -1525);
	i = printf("Printf 2: %x\n\n", -1525);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", 0);
	i = printf("Printf 2: %X\n\n", 0);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", 44);
	i = printf("Printf 2: %X\n\n", 44);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", 155);
	i = printf("Printf 2: %X\n\n", 155);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", 356);
	i = printf("Printf 2: %X\n\n", 356);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 5: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", 34242);
	i = printf("Printf 2: %X\n\n", 34242);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 6: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", UINT_MAX);
	i = printf("Printf 2: %X\n\n", UINT_MAX);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 7: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", -1);
	i = printf("Printf 2: %X\n\n", -1);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 8: Hexa_Upper\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %X\n\n", -1525);
	i = printf("Printf 2: %X\n\n", -1525);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	z = ft_printf("asdasd%sadsad%dasdad%s\n\n", "HEllo", 5, "Name");
	i = printf("asdasd%sadsad%dasdad%s\n\n", "HEllo", 5, "Name");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	return (0);
}
