#include "ft_printf.h"
#include <limits.h>

int	main(void)
{
	int	i;
	int	z;
	void *ptr;
	int	*intp;
	char *charp;
	char *strp;
	unsigned int *unsignedp;

	ft_putstr_fd("Test 1: Char\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %c\n", 'A');
	i = printf("Printf 2: %c\n\n", 'A');
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Char\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %c\n", 'A');
	i = printf("Printf 2: %c\n\n", 'A');
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Char\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %c\n", -1);
	i = printf("Printf 2: %c\n\n", -1);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", 10);
	i = ft_printf("Printf 1: %i\n\n", -10);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	z = printf("Printf 2: %i\n", 10);
	i = printf("Printf 2: %i\n\n", -10);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", 5324);
	i = ft_printf("Printf 1: %i\n\n", -5324);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	z = printf("Printf 2: %i\n", 5324);
	i = printf("Printf 2: %i\n\n", -5324);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: Int\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %i\n", INT_MAX);
	i = ft_printf("Printf 1: %i\n\n", INT_MIN);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	z = printf("Printf 2: %i\n", INT_MAX);
	i = printf("Printf 2: %i\n\n", INT_MIN);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "Hello World!");
	i = printf("Printf 2: %s\n\n", "Hello World!");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "asdasdasdasdasdsadasdasdasdasdasdsadsadsadsadsadsadad");
	i = printf("Printf 2: %s\n\n", "asdasdasdasdasdsadasdasdasdasdasdsadsadsadsadsadsadad");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "");
	i = printf("Printf 2: %s\n\n", "");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: String\n---------------\n\n", 1);
	z = ft_printf("Printf 1: %s\n\n", "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
	i = printf("Printf 2: %s\n\n", "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Pointer\n---------------\n\n", 1);
	int	a = 15;
	intp = &a;
	z = ft_printf("Printf 1: %p\n\n", intp);
	i = printf("Printf 2: %p\n\n", intp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 2: Pointer\n---------------\n\n", 1);
	char	b = 'A';
	charp = &b;
	z = ft_printf("Printf 1: %p\n\n", charp);
	i = printf("Printf 2: %p\n\n", charp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 3: Pointer\n---------------\n\n", 1);
	char *c = "Hello";
	strp = c;
	z = ft_printf("Printf 1: %p\n\n", strp);
	i = printf("Printf 2: %p\n\n", strp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 4: Pointer\n---------------\n\n", 1);
	unsigned int d = 40968;
	unsignedp = &d;
	z = ft_printf("Printf 1: %p\n\n", unsignedp);
	i = printf("Printf 2: %p\n\n", unsignedp);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	ft_putstr_fd("Test 1: Pointer\n---------------\n\n", 1);
	ptr = NULL;
	z = ft_printf("Printf 1: %p\n\n", ptr);
	i = printf("Printf 2: %p\n\n", ptr);
	printf("Return: %d\n", z);
	printf("Return: %d\n\n", i);
	return (0);
}
